plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

title: Helios
author:
  name: Ztarbox and laserkraft
  email: ""
# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Our journey of planning, launching and operating the Helios Validator 
  on the Solana blockchain.
minima:
  skin: auto
  show_excerpts: true
  social_links:
    - platform: github
      user_url: "https://github.com/Ztarbox/Helios"
      title: Source of this Website
  # If you want to link only specific pages in your header, uncomment this and add the path to the pages in
  # order as they should show up.
  # header_pages:
  #   - about.md